local Plug = vim.fn["plug#"]

vim.call("plug#begin")

Plug('catppuccin/nvim', { ['as'] = 'catppuccin' })
Plug('goolord/alpha-nvim')
Plug('nvim-lualine/lualine.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug('nvim-tree/nvim-tree.lua')
Plug('folke/which-key.nvim')
Plug('lewis6991/gitsigns.nvim')
Plug('romgrk/barbar.nvim')
Plug('nvim-treesitter/nvim-treesitter')
Plug('ibhagwan/fzf-lua')
Plug('numToStr/Comment.nvim')
Plug('numToStr/FTerm.nvim')
Plug('windwp/nvim-autopairs')
Plug('norcalli/nvim-colorizer.lua')
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-cmdline')
Plug('hrsh7th/nvim-cmp')
Plug('L3MON4D3/LuaSnip')
Plug('saadparwaiz1/cmp_luasnip')
Plug('rafamadriz/friendly-snippets')
Plug('habamax/vim-godot')

vim.call("plug#end")

require("config.theme")
require("config.mappings")
require("config.options")
require("config.godot")

require("plugins.catppuccin")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.alpha")
require("plugins.whichkey")
require("plugins.barbar")
require("plugins.fterm")
require("plugins.fzf")
require("plugins.gitsigns")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.colorizer")
require("plugins.lspconfig")
require("plugins.nvim-cmp")

load_theme()
